"""Centralized Node Contract Registry — all 11 standard node types."""

from app.runtime.node_types import NodeType
from app.runtime.contract_registry import NodeContract, SecurityLevel

# ponytail: placeholder execute_fn — the real engine functions are wired in
# during app startup (see app/main.py lifespan) so we don't create import cycles
# or initialize heavy singletons at module load time.

_PLACEHOLDER = lambda inputs: {}  # noqa: E731


REGISTRY: dict[NodeType, NodeContract] = {
    NodeType.FILE_PARSE: NodeContract(
        node_type=NodeType.FILE_PARSE,
        input_schema={
            "type": "object",
            "required": ["file_path"],
            "properties": {"file_path": {"type": "string"}},
        },
        output_schema={"type": "object"},
        cacheable=False,
        retryable=True,
        deterministic=True,
        replay_required=True,
        degradable=False,
        security_level=SecurityLevel.STANDARD,
        execute_fn=_PLACEHOLDER,
    ),
    NodeType.OCR: NodeContract(
        node_type=NodeType.OCR,
        input_schema={
            "type": "object",
            "required": ["file_path"],
            "properties": {"file_path": {"type": "string"}},
        },
        output_schema={"type": "object"},
        cacheable=True,
        retryable=True,
        deterministic=False,
        replay_required=True,
        degradable=True,
        security_level=SecurityLevel.STANDARD,
        execute_fn=_PLACEHOLDER,
    ),
    NodeType.TEXT_NORMALIZE: NodeContract(
        node_type=NodeType.TEXT_NORMALIZE,
        input_schema={"type": "object"},
        output_schema={"type": "object"},
        cacheable=False,
        retryable=False,
        deterministic=True,
        replay_required=True,
        degradable=False,
        security_level=SecurityLevel.STANDARD,
        execute_fn=_PLACEHOLDER,
    ),
    NodeType.SECTION_SPLIT: NodeContract(
        node_type=NodeType.SECTION_SPLIT,
        input_schema={"type": "object"},
        output_schema={"type": "object"},
        cacheable=False,
        retryable=False,
        deterministic=True,
        replay_required=True,
        degradable=False,
        security_level=SecurityLevel.STANDARD,
        execute_fn=_PLACEHOLDER,
    ),
    NodeType.RULE_CHECK: NodeContract(
        node_type=NodeType.RULE_CHECK,
        input_schema={"type": "object"},
        output_schema={"type": "object"},
        cacheable=False,
        retryable=True,
        deterministic=True,
        replay_required=True,
        degradable=False,
        security_level=SecurityLevel.HIGH,
        execute_fn=_PLACEHOLDER,
    ),
    NodeType.LLM_CHECK: NodeContract(
        node_type=NodeType.LLM_CHECK,
        input_schema={"type": "object"},
        output_schema={"type": "object"},
        cacheable=False,
        retryable=True,
        deterministic=False,
        replay_required=True,
        degradable=True,
        security_level=SecurityLevel.HIGH,
        execute_fn=_PLACEHOLDER,
    ),
    NodeType.EVIDENCE_MAPPING: NodeContract(
        node_type=NodeType.EVIDENCE_MAPPING,
        input_schema={"type": "object"},
        output_schema={"type": "object"},
        cacheable=False,
        retryable=True,
        deterministic=True,
        replay_required=True,
        degradable=True,
        security_level=SecurityLevel.STANDARD,
        execute_fn=_PLACEHOLDER,
    ),
    NodeType.FUSION: NodeContract(
        node_type=NodeType.FUSION,
        input_schema={"type": "object"},
        output_schema={"type": "object"},
        cacheable=False,
        retryable=False,
        deterministic=True,
        replay_required=True,
        degradable=False,
        security_level=SecurityLevel.HIGH,
        execute_fn=_PLACEHOLDER,
    ),
    NodeType.POLICY_KERNEL: NodeContract(
        node_type=NodeType.POLICY_KERNEL,
        input_schema={"type": "object"},
        output_schema={"type": "object"},
        cacheable=False,
        retryable=False,
        deterministic=True,
        replay_required=True,
        degradable=False,
        security_level=SecurityLevel.CRITICAL,
        execute_fn=_PLACEHOLDER,
    ),
    NodeType.REPORT_BUILD: NodeContract(
        node_type=NodeType.REPORT_BUILD,
        input_schema={"type": "object"},
        output_schema={"type": "object"},
        cacheable=False,
        retryable=False,
        deterministic=True,
        replay_required=False,
        degradable=True,
        security_level=SecurityLevel.STANDARD,
        execute_fn=_PLACEHOLDER,
    ),
    NodeType.FEEDBACK_SNAPSHOT: NodeContract(
        node_type=NodeType.FEEDBACK_SNAPSHOT,
        input_schema={"type": "object"},
        output_schema={"type": "object"},
        cacheable=False,
        retryable=False,
        deterministic=True,
        replay_required=False,
        degradable=True,
        security_level=SecurityLevel.STANDARD,
        execute_fn=_PLACEHOLDER,
    ),
}
